![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
# AQUÍ VA VUESTRO CÓDIGO
my_array = np.arange(0,10)

print(my_array)

print(np.arange(start=9,stop=-1,step=-2))

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [3]:
# AQUÍ VA VUESTRO CÓDIGO
print("Desde el octavo hasta el septimo,",my_array[-3:-1][::-1])

Desde el octavo hasta el septimo, [8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [4]:
# AQUÍ VA VUESTRO CÓDIGO
print(my_array[:3][::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [5]:
# AQUÍ VA VUESTRO CÓDIGO
x = np.arange(1,21).reshape(4,5)

print(x)

print(x.reshape(5,4))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [6]:
# AQUÍ VA VUESTRO CÓDIGO
print("2 primeras filas y 2 primeras columnas\n",x[:2,:2])

2 primeras filas y 2 primeras columnas
 [[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [7]:
# AQUÍ VA VUESTRO CÓDIGO
print("la primera y la tercera fila cada dos columnas\n",x[0::2,::2])

la primera y la tercera fila cada dos columnas
 [[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [8]:
# AQUÍ VA VUESTRO CÓDIGO
print("Invertir las 3 primeras columnas\n",x[0:3,::-1])

Invertir las 3 primeras columnas
 [[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [9]:
# AQUÍ VA VUESTRO CÓDIGO
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

print(x[x == "Loro"])

['Loro' 'Loro']


In [10]:
x

lista_filtrada = []

for elem in x:
    if elem == "Loro":
        lista_filtrada.append(elem)
print(lista_filtrada)

['Loro', 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [11]:
# AQUÍ VA VUESTRO CÓDIGO

array_9 = np.arange(20).reshape(2,10)
print(array_9)

x1,x2 = np.hsplit(array_9,[5])

print(x1)

print(x2)



[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [12]:
# AQUÍ VA VUESTRO CÓDIGO

array_10 = np.zeros((10))

print(array_10)

array_10[3] = 1

array_10



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [13]:
# AQUÍ VA VUESTRO CÓDIGO

vector_11 = np.arange(10,50)

vector_11

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [14]:
vector_11_inv = vector_11[::-1]

vector_11_inv

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [15]:
# AQUÍ VA VUESTRO CÓDIGO

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [16]:
# AQUÍ VA VUESTRO CÓDIGO
matriz_13 = np.random.random(100).reshape(10,10)

matriz_13

array([[0.60530625, 0.34685983, 0.38327723, 0.98400474, 0.88895566,
        0.20474   , 0.36606699, 0.26898572, 0.43139364, 0.35553456],
       [0.07432752, 0.04134588, 0.93557193, 0.00202903, 0.62019297,
        0.08089065, 0.69380086, 0.43228509, 0.23136047, 0.47090982],
       [0.5445827 , 0.48044262, 0.92330355, 0.06800725, 0.48264491,
        0.42721954, 0.00175424, 0.45799288, 0.58155419, 0.97047424],
       [0.29274116, 0.04812011, 0.23295593, 0.1637117 , 0.0363719 ,
        0.16838099, 0.58473341, 0.93220216, 0.63322419, 0.8956788 ],
       [0.17403848, 0.44107021, 0.96690056, 0.33891017, 0.20238219,
        0.0335012 , 0.25116814, 0.09276503, 0.61058491, 0.17197732],
       [0.43568661, 0.47243196, 0.43265827, 0.16252873, 0.57280298,
        0.99729356, 0.59781483, 0.86341826, 0.68629692, 0.35940068],
       [0.49342295, 0.95319419, 0.77259165, 0.16798351, 0.36662123,
        0.89812893, 0.14072628, 0.05421348, 0.2541793 , 0.14898968],
       [0.561621  , 0.97002811, 0.7232842

In [17]:
max = matriz_13.max()

min = matriz_13.min()

print(max,"\n",min)



0.99729356020358 
 0.0017542435163510062


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [18]:
# AQUÍ VA VUESTRO CÓDIGO

vector_14 = np.random.random(30)

print(np.mean(vector_14))

0.485496576069819


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [19]:
# AQUÍ VA VUESTRO CÓDIGO

array_15 = np.ones((4,4))

array_15

array_15[1:3,1:3] = 0

array_15

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [20]:
# AQUÍ VA VUESTRO CÓDIGO



submatrix = np.array([[0, 1], [1, 0]])


repeated_submatrix = np.tile(submatrix, (4, 4))

print(repeated_submatrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [21]:
# AQUÍ VA VUESTRO CÓDIGO
submatrix = np.array([[0, 1], [1, 0]])


repeated_submatrix = np.tile(submatrix, (4, 4))

print(repeated_submatrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [22]:
# AQUÍ VA VUESTRO CÓDIGO
matriz_18 = np.random.random(25)

col_means = np.mean(matriz_18, axis = 0)

matriz_18_norm = matriz_18 - col_means / np.mean(matriz_18, axis = 0)

print(matriz_18_norm)

[-0.1618758  -0.73695308 -0.32014185 -0.27637892 -0.19584728 -0.52377332
 -0.17977076 -0.77279898 -0.65692859 -0.41302881 -0.37945249 -0.39646076
 -0.85176881 -0.78027139 -0.01124061 -0.44687242 -0.59350474 -0.71287828
 -0.84861116 -0.09771747 -0.41301072 -0.64872189 -0.86699821 -0.46020933
 -0.82439244]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [41]:
# AQUÍ VA VUESTRO CÓDIGO
array_19 = np.arange(0,11)

array_19

array_19[4:8] = -1

print(array_19)

nueva_array19 = [valor for valor in array_19 if valor != -1]

nueva_array19


[ 0  1  2  3 -1 -1 -1 -1  8  9 10]


[0, 1, 2, 3, 8, 9, 10]